site_name: è€æœçš„ç¬”è®°ä»“åº“
site_url: https://metaldudu.github.io/notes
site_author: MetalDudu
site_description: è€æœçš„ç¬”è®°ä»“åº“

# [UI]
## [top]
theme:
  name: material
  logo: assets/logo.png
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: slate # å¤œé—´æ¨¡å¼
    primary: teal 
    accent: deep orange # é“¾æ¥ç­‰å¯äº¤äº’å…ƒä»¶çš„é«˜äº®è‰²
    toggle:
    icon: material/lightbulb # å›¾æ ‡
    name: åˆ‡æ¢è‡³æ—¥é—´æ¨¡å¼ # é¼ æ ‡æ‚¬æµ®æç¤º
  - media: "(prefers-color-scheme: dark)"
    scheme: default # æ—¥é—´æ¨¡å¼
    primary: blue grey
    accent: orange
    toggle:
    icon: material/lightbulb-outline
    name: åˆ‡æ¢è‡³å¤œé—´æ¨¡å¼
  features:
  - navigation.tabs # ä½¿ç”¨Tabæ¥è¿›è¡Œåˆ†ç±»
  - navigation.sections
  - navigation.top # è¿”å›é¡¶éƒ¨çš„æŒ‰é’® åœ¨ä¸Šæ»‘æ—¶å‡ºç°
  - navigation.indexes # Tabä¼šæœ‰ä¸€ä¸ªindex.md è€Œä¸æ˜¯åœ¨æ‰“å¼€Tabæ—¶æ‰“å¼€ç¬¬ä¸€ç¯‡æ–‡ç« 
  #- navigation.expand # æ‰“å¼€Tabæ—¶å·¦ä¾§ç›®å½•å…¨éƒ¨å±•å¼€
  - search.suggest # æœç´¢è¾“å…¥ä¸€äº›å­—æ¯æ—¶æ¨èè¡¥å…¨æ•´ä¸ªå•è¯
  - search.highlight # æœç´¢å‡ºçš„æ–‡ç« å…³é”®è¯åŠ å…¥é«˜äº®
  - content.code.copy # å¯ä»¥é€šè¿‡æŒ‰é’®å¤åˆ¶ä»£ç 
  language: zh # ä¸€äº›æç¤ºæ€§çš„æ–‡å­—ä¼šå˜æˆä¸­æ–‡
  icon:
  repo: fontawesome/brands/github

## [bottom-right corner]
extra:
  social: # icons
  - icon: simple/douban
    link: https://www.douban.com/people/metaldudu
  - icon: fontawesome/brands/mastodon
    link: https://m.cmx.im/@metaldudu
  - icon: fontawesome/brands/github
    link: https://github.com/metaldudu

# å¯¼èˆª

nav:

  - LANG:
    - english-listening-resourceï¼šenglish-listening-resource.md
    - little-foxï¼šlittle-fox.md
    - indexï¼šindex.md
    - black-catï¼šblack-cat.md
  - RES:
    - chinese-song-bpmï¼šchinese-song-bpm.md
    - chinese-zodiacï¼šchinese-zodiac.md
    - online-free-movieï¼šonline-free-movie.md
    - free-fontsï¼šfree-fonts.md
    - ebook-websiteï¼šebook-website.md
    - movie-websiteï¼šmovie-website.md
    - ğŸŠmore-websitesï¼šğŸŠmore-websites.md
    - indexï¼šindex.md
    - things-to-buyï¼šthings-to-buy.md
    - good-habitsï¼šgood-habits.md
  - READ:
    - indexï¼šindex.md
    - åå¹´é˜…è¯»è®¡åˆ’ï¼šåå¹´é˜…è¯»è®¡åˆ’.md
  - READ/LIST:
    - NEAç¥¨é€‰100æœ¬å„¿ç«¥ä¹¦ï¼šNEAç¥¨é€‰100æœ¬å„¿ç«¥ä¹¦.md
    - å¤§å®¶å°ä¹¦ï¼šå¤§å®¶å°ä¹¦.md
    - äºšé©¬é€Š100æœ¬ç«¥ä¹¦ï¼šäºšé©¬é€Š100æœ¬ç«¥ä¹¦.md
    - ä¹¦å•-2017å…¬ä¼—å·è¯»è€…æ¨èä¹¦ç›®ï¼šä¹¦å•-2017å…¬ä¼—å·è¯»è€…æ¨èä¹¦ç›®.md
    - äºšé©¬é€Š100æœ¬å¿…è¯»ä¹¦ï¼šäºšé©¬é€Š100æœ¬å¿…è¯»ä¹¦.md
    - å¤§æ°‘å¤§å›½40å¹´40æœ¬ä¹¦ï¼šå¤§æ°‘å¤§å›½40å¹´40æœ¬ä¹¦.md
    - 100æœ¬æœ€ä½³ä¾¦æ¢å°è¯´ï¼š100æœ¬æœ€ä½³ä¾¦æ¢å°è¯´.md
    - ä¹¦å•-2016å…¬ä¼—å·è¯»è€…æ¨èæ•°ç›®ï¼šä¹¦å•-2016å…¬ä¼—å·è¯»è€…æ¨èæ•°ç›®.md
    - å¡å†…åŸºå¥–ï¼šå¡å†…åŸºå¥–.md
    - çº½ä¼¯ç‘å¥–ï¼šçº½ä¼¯ç‘å¥–.md
  - K:
    - indexï¼šindex.md
    - fav-ted-talksï¼šfav-ted-talks.md
  - K/NOTE:
    - MOOC-ç¾å›½æ–‡åŒ–ï¼šMOOC-ç¾å›½æ–‡åŒ–.md
    - celebrity-and-morden-chinaï¼šcelebrity-and-morden-china.md
    - learning-how-to-learnï¼šlearning-how-to-learn.md
    - justiceï¼šjustice.md
    - criminal-lawï¼šcriminal-law.md
    - chinese-novelï¼šchinese-novel.md
    - tan-jingï¼štan-jing.md
    - europe-historyï¼šeurope-history.md
    - game-psychologyï¼šgame-psychology.md
  - TECH:
    - minimalist-launchersï¼šminimalist-launchers.md
    - nasï¼šnas.md
    - 12-tips-to-manage-filesï¼š12-tips-to-manage-files.md
    - Firefoxæµè§ˆå™¨ï¼šFirefoxæµè§ˆå™¨.md
    - hotkey-cheetsheetï¼šhotkey-cheetsheet.md
    - cmusï¼šcmus.md
    - ArchLinuxï¼šArchLinux.md
    - koboï¼škobo.md
    - vimwikiï¼švimwiki.md
    - Obsidianï¼šObsidian.md
    - å°å±æ‰‹æœºå‚æ•°å¯¹æ¯”ï¼šå°å±æ‰‹æœºå‚æ•°å¯¹æ¯”.md
    - manage-downloaded-ebookï¼šmanage-downloaded-ebook.md
    - win-softwareï¼šwin-software.md
    - linux-softwareï¼šlinux-software.md
    - kittyï¼škitty.md
    - tradition-colorï¼štradition-color.md
    - goldendictï¼šgoldendict.md
    - indexï¼šindex.md
    - mkdocsï¼šmkdocs.md
    - manage-downloaded-mediaï¼šmanage-downloaded-media.md
    - android-appï¼šandroid-app.md
    - ffmpegï¼šffmpeg.md
  - FUN:
    - indexï¼šindex.md
  - FUN/GAME:
    - XBOXï¼šXBOX.md
    - DeadCellsï¼šDeadCells.md
    - åœ¨çº¿å°æ¸¸æˆï¼šåœ¨çº¿å°æ¸¸æˆ.md
    - å–œæ¬¢çš„æ¸¸æˆï¼šå–œæ¬¢çš„æ¸¸æˆ.md
    - NSï¼šNS.md
  - FUN/MOVIE:
    - æ¯”åˆ©Â·æ€€å¾·ï¼šæ¯”åˆ©Â·æ€€å¾·.md
    - åº“å¸ƒé‡Œå…‹ï¼šåº“å¸ƒé‡Œå…‹.md
    - ä¼Šæ–¯ç‰¹ä¼å¾·ï¼šä¼Šæ–¯ç‰¹ä¼å¾·.md
    - æŸ¥ç†Â·è€ƒå¤«æ›¼ï¼šæŸ¥ç†Â·è€ƒå¤«æ›¼.md
  - WRITE:
    - 2015ï¼š2015.md
    - 2016ï¼š2016.md
    - indexï¼šindex.md
    - 2017ï¼š2017.md


# 
# copy from https://github.com/Yang-Xijie/yang-xijie.github.io/blob/main/mkdocs.yml
