site_name: è€æœçš„ç¬”è®°ä»“åº“
site_url: https://metaldudu.github.io/notes
site_author: MetalDudu
site_description: è€æœçš„ç¬”è®°ä»“åº“

# [UI]
## [top]
theme:
  name: material
  logo: assets/logo.png
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: slate # å¤œé—´æ¨¡å¼
    primary: teal 
    accent: deep orange # é“¾æ¥ç­‰å¯äº¤äº’å…ƒä»¶çš„é«˜äº®è‰²
    toggle:
    icon: material/lightbulb # å›¾æ ‡
    name: åˆ‡æ¢è‡³æ—¥é—´æ¨¡å¼ # é¼ æ ‡æ‚¬æµ®æç¤º
  - media: "(prefers-color-scheme: dark)"
    scheme: default # æ—¥é—´æ¨¡å¼
    primary: blue grey
    accent: orange
    toggle:
    icon: material/lightbulb-outline
    name: åˆ‡æ¢è‡³å¤œé—´æ¨¡å¼
  features:
  - navigation.tabs # ä½¿ç”¨Tabæ¥è¿›è¡Œåˆ†ç±»
  - navigation.sections
  - navigation.top # è¿”å›é¡¶éƒ¨çš„æŒ‰é’® åœ¨ä¸Šæ»‘æ—¶å‡ºç°
  - navigation.indexes # Tabä¼šæœ‰ä¸€ä¸ªindex.md è€Œä¸æ˜¯åœ¨æ‰“å¼€Tabæ—¶æ‰“å¼€ç¬¬ä¸€ç¯‡æ–‡ç« 
  #- navigation.expand # æ‰“å¼€Tabæ—¶å·¦ä¾§ç›®å½•å…¨éƒ¨å±•å¼€
  - search.suggest # æœç´¢è¾“å…¥ä¸€äº›å­—æ¯æ—¶æ¨èè¡¥å…¨æ•´ä¸ªå•è¯
  - search.highlight # æœç´¢å‡ºçš„æ–‡ç« å…³é”®è¯åŠ å…¥é«˜äº®
  - content.code.copy # å¯ä»¥é€šè¿‡æŒ‰é’®å¤åˆ¶ä»£ç 
  language: zh # ä¸€äº›æç¤ºæ€§çš„æ–‡å­—ä¼šå˜æˆä¸­æ–‡
  icon:
  repo: fontawesome/brands/github

## [bottom-right corner]
extra:
  social: # icons
  - icon: simple/douban
    link: https://www.douban.com/people/metaldudu
  - icon: fontawesome/brands/mastodon
    link: https://m.cmx.im/@metaldudu
  - icon: fontawesome/brands/github
    link: https://github.com/metaldudu

# å¯¼èˆª

nav:
  - GAME:
    - index: GAME/index.md
    - XBOX: GAME/XBOX.md
    - æ­»äº¡ç»†èƒåœ°å›¾: GAME/æ­»äº¡ç»†èƒåœ°å›¾.md
    - åœ¨çº¿å°æ¸¸æˆ: GAME/åœ¨çº¿å°æ¸¸æˆ.md
    - å–œæ¬¢çš„æ¸¸æˆ: GAME/å–œæ¬¢çš„æ¸¸æˆ.md
    - NS: GAME/NS.md
  - RES:
    - index: RES/index.md
    - chinese-song-bpm: RES/chinese-song-bpm.md
    - chinese-zodiac: RES/chinese-zodiac.md
    - online-free-movie: RES/online-free-movie.md
    - free-fonts: RES/free-fonts.md
    - ebook-website: RES/ebook-website.md
    - movie-website: RES/movie-website.md
    - ğŸŠmore-websites: RES/ğŸŠmore-websites.md
    - things-to-buy: RES/things-to-buy.md
    - good-habits: RES/good-habits.md
  - READ:
    - index: READ/index.md
    - NEAç¥¨é€‰100æœ¬å„¿ç«¥ä¹¦: READ/NEAç¥¨é€‰100æœ¬å„¿ç«¥ä¹¦.md
    - å¤§å®¶å°ä¹¦: READ/å¤§å®¶å°ä¹¦.md
    - äºšé©¬é€Š100æœ¬ç«¥ä¹¦: READ/äºšé©¬é€Š100æœ¬ç«¥ä¹¦.md
    - ä¹¦å•-2017å…¬ä¼—å·è¯»è€…æ¨èä¹¦ç›®: READ/ä¹¦å•-2017å…¬ä¼—å·è¯»è€…æ¨èä¹¦ç›®.md
    - äºšé©¬é€Š100æœ¬å¿…è¯»ä¹¦: READ/äºšé©¬é€Š100æœ¬å¿…è¯»ä¹¦.md
    - å¤§æ°‘å¤§å›½40å¹´40æœ¬ä¹¦: READ/å¤§æ°‘å¤§å›½40å¹´40æœ¬ä¹¦.md
    - 100æœ¬æœ€ä½³ä¾¦æ¢å°è¯´: READ/100æœ¬æœ€ä½³ä¾¦æ¢å°è¯´.md
    - ä¹¦å•-2016å…¬ä¼—å·è¯»è€…æ¨èæ•°ç›®: READ/ä¹¦å•-2016å…¬ä¼—å·è¯»è€…æ¨èæ•°ç›®.md
    - å¡å†…åŸºå¥–: READ/å¡å†…åŸºå¥–.md
    - çº½ä¼¯ç‘å¥–: READ/çº½ä¼¯ç‘å¥–.md
    - åå¹´é˜…è¯»è®¡åˆ’: READ/åå¹´é˜…è¯»è®¡åˆ’.md
  - K:
    - index: K/index.md
    - MOOC-ç¾å›½æ–‡åŒ–: K/MOOC-ç¾å›½æ–‡åŒ–.md
    - celebrity-and-morden-china: K/celebrity-and-morden-china.md
    - learning-how-to-learn: K/learning-how-to-learn.md
    - justice: K/justice.md
    - criminal-law: K/criminal-law.md
    - chinese-novel: K/chinese-novel.md
    - tan-jing: K/tan-jing.md
    - europe-history: K/europe-history.md
    - game-psychology: K/game-psychology.md
    - fav-ted-talks: K/fav-ted-talks.md
  - MOVIE:
    - index: MOVIE/index.md
    - æ¯”åˆ©Â·æ€€å¾·: MOVIE/æ¯”åˆ©Â·æ€€å¾·.md
    - åº“å¸ƒé‡Œå…‹: MOVIE/åº“å¸ƒé‡Œå…‹.md
    - ä¼Šæ–¯ç‰¹ä¼å¾·: MOVIE/ä¼Šæ–¯ç‰¹ä¼å¾·.md
    - æŸ¥ç†Â·è€ƒå¤«æ›¼: MOVIE/æŸ¥ç†Â·è€ƒå¤«æ›¼.md
  - TECH:
    - index: TECH/index.md
    - minimalist-launchers: TECH/minimalist-launchers.md
    - nas: TECH/nas.md
    - 12-tips-to-manage-files: TECH/12-tips-to-manage-files.md
    - Firefoxæµè§ˆå™¨: TECH/Firefoxæµè§ˆå™¨.md
    - hotkey-cheetsheet: TECH/hotkey-cheetsheet.md
    - cmus: TECH/cmus.md
    - ArchLinux: TECH/ArchLinux.md
    - kobo: TECH/kobo.md
    - vimwiki: TECH/vimwiki.md
    - Obsidian: TECH/Obsidian.md
    - å°å±æ‰‹æœºå‚æ•°å¯¹æ¯”: TECH/å°å±æ‰‹æœºå‚æ•°å¯¹æ¯”.md
    - manage-downloaded-ebook: TECH/manage-downloaded-ebook.md
    - win-software: TECH/win-software.md
    - linux-software: TECH/linux-software.md
    - kitty: TECH/kitty.md
    - tradition-color: TECH/tradition-color.md
    - goldendict: TECH/goldendict.md
    - mkdocs: TECH/mkdocs.md
    - manage-downloaded-media: TECH/manage-downloaded-media.md
    - android-app: TECH/android-app.md
    - ffmpeg: TECH/ffmpeg.md
  - WRITE:
    - index: WRITE/index.md
    - 2015: WRITE/2015.md
    - 2016: WRITE/2016.md
    - 2017: WRITE/2017.md



# 
# copy from https://github.com/Yang-Xijie/yang-xijie.github.io/blob/main/mkdocs.yml
