site_name: è€æœçš„ç¬”è®°ä»“åº“
site_url: https://metaldudu.github.io/notes
site_author: MetalDudu
site_description: è€æœçš„ç¬”è®°ä»“åº“

# [UI]
## [top]
theme:
  name: material
  logo: assets/logo.png
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: slate # å¤œé—´æ¨¡å¼
    primary: teal 
    accent: deep orange # é“¾æ¥ç­‰å¯äº¤äº’å…ƒä»¶çš„é«˜äº®è‰²
    toggle:
    icon: material/lightbulb # å›¾æ ‡
    name: åˆ‡æ¢è‡³æ—¥é—´æ¨¡å¼ # é¼ æ ‡æ‚¬æµ®æç¤º
  - media: "(prefers-color-scheme: dark)"
    scheme: default # æ—¥é—´æ¨¡å¼
    primary: blue grey
    accent: orange
    toggle:
    icon: material/lightbulb-outline
    name: åˆ‡æ¢è‡³å¤œé—´æ¨¡å¼
  features:
  - navigation.tabs # ä½¿ç”¨Tabæ¥è¿›è¡Œåˆ†ç±»
  - navigation.sections
  - navigation.top # è¿”å›é¡¶éƒ¨çš„æŒ‰é’® åœ¨ä¸Šæ»‘æ—¶å‡ºç°
  - navigation.indexes # Tabä¼šæœ‰ä¸€ä¸ªindex.md è€Œä¸æ˜¯åœ¨æ‰“å¼€Tabæ—¶æ‰“å¼€ç¬¬ä¸€ç¯‡æ–‡ç« 
  #- navigation.expand # æ‰“å¼€Tabæ—¶å·¦ä¾§ç›®å½•å…¨éƒ¨å±•å¼€
  - search.suggest # æœç´¢è¾“å…¥ä¸€äº›å­—æ¯æ—¶æ¨èè¡¥å…¨æ•´ä¸ªå•è¯
  - search.highlight # æœç´¢å‡ºçš„æ–‡ç« å…³é”®è¯åŠ å…¥é«˜äº®
  - content.code.copy # å¯ä»¥é€šè¿‡æŒ‰é’®å¤åˆ¶ä»£ç 
  language: zh # ä¸€äº›æç¤ºæ€§çš„æ–‡å­—ä¼šå˜æˆä¸­æ–‡
  icon:
  repo: fontawesome/brands/github

## [bottom-right corner]
extra:
  social: # icons
  - icon: simple/douban
    link: https://www.douban.com/people/metaldudu
  - icon: fontawesome/brands/mastodon
    link: https://m.cmx.im/@metaldudu
  - icon: fontawesome/brands/github
    link: https://github.com/metaldudu

# å¯¼èˆª

nav:

  - LANG:
    - english-listening-resource: english-listening-resource.md
    - little-fox: little-fox.md
    - index: index.md
    - black-cat: black-cat.md
  - RES:
    - chinese-song-bpm: chinese-song-bpm.md
    - chinese-zodiac: chinese-zodiac.md
    - online-free-movie: online-free-movie.md
    - free-fonts: free-fonts.md
    - ebook-website: ebook-website.md
    - movie-website: movie-website.md
    - ğŸŠmore-websites: ğŸŠmore-websites.md
    - index: index.md
    - things-to-buy: things-to-buy.md
    - good-habits: good-habits.md
  - READ:
    - index: index.md
    - åå¹´é˜…è¯»è®¡åˆ’: åå¹´é˜…è¯»è®¡åˆ’.md
  - READ/LIST:
    - NEAç¥¨é€‰100æœ¬å„¿ç«¥ä¹¦: NEAç¥¨é€‰100æœ¬å„¿ç«¥ä¹¦.md
    - å¤§å®¶å°ä¹¦: å¤§å®¶å°ä¹¦.md
    - äºšé©¬é€Š100æœ¬ç«¥ä¹¦: äºšé©¬é€Š100æœ¬ç«¥ä¹¦.md
    - ä¹¦å•-2017å…¬ä¼—å·è¯»è€…æ¨èä¹¦ç›®: ä¹¦å•-2017å…¬ä¼—å·è¯»è€…æ¨èä¹¦ç›®.md
    - äºšé©¬é€Š100æœ¬å¿…è¯»ä¹¦: äºšé©¬é€Š100æœ¬å¿…è¯»ä¹¦.md
    - å¤§æ°‘å¤§å›½40å¹´40æœ¬ä¹¦: å¤§æ°‘å¤§å›½40å¹´40æœ¬ä¹¦.md
    - 100æœ¬æœ€ä½³ä¾¦æ¢å°è¯´: 100æœ¬æœ€ä½³ä¾¦æ¢å°è¯´.md
    - ä¹¦å•-2016å…¬ä¼—å·è¯»è€…æ¨èæ•°ç›®: ä¹¦å•-2016å…¬ä¼—å·è¯»è€…æ¨èæ•°ç›®.md
    - å¡å†…åŸºå¥–: å¡å†…åŸºå¥–.md
    - çº½ä¼¯ç‘å¥–: çº½ä¼¯ç‘å¥–.md
  - K:
    - index: index.md
    - fav-ted-talks: fav-ted-talks.md
  - K/NOTE:
    - MOOC-ç¾å›½æ–‡åŒ–: MOOC-ç¾å›½æ–‡åŒ–.md
    - celebrity-and-morden-china: celebrity-and-morden-china.md
    - learning-how-to-learn: learning-how-to-learn.md
    - justice: justice.md
    - criminal-law: criminal-law.md
    - chinese-novel: chinese-novel.md
    - tan-jing: tan-jing.md
    - europe-history: europe-history.md
    - game-psychology: game-psychology.md


# 
# copy from https://github.com/Yang-Xijie/yang-xijie.github.io/blob/main/mkdocs.yml
